#%Module1.0#####################################################################
#
# ${AUTOMATIC_BUILD_WARNING}
#

set     INSTALLDIR      ${TARGET}

proc ModulesHelp { } {
	global INSTALLDIR
        puts stderr "================================================================================
NEST Simulator ${VERSION} (${VARIANT})
================================================================================

   NEST is a simulator for spiking neural network models that focuses on the
   dynamics, size and structure of neural systems rather than on the exact
   morphology of individual neurons.

   Load this modulefile instead of the usual 'source .../bin/nest_vars.sh' to
   initialize all environment variables.

   For help visit:  https://nest-simulator.org/documentation.
"
        set fp [open "\$INSTALLDIR/ConfigurationSummary.txt" r]
        puts stderr [read \$fp];
        close \$fp;
        puts stderr "Module settings:
INSTALLDIR:  	\$INSTALLDIR"
}

module-whatis   "NEST spiking neural network simulator, version ${VERSION} (${VARIANT} build)"

conflict ${PACKAGE}

################################################################################
# from \$INSTALLDIR/bin/nest_vars.sh
# 
# NEST is installed here. When you relocate NEST, change this variable.
setenv          NEST_INSTALL_DIR        \$INSTALLDIR

# NEST finds standard *.sli files \$NEST_DATA_DIR/sli
setenv          NEST_DATA_DIR           \$INSTALLDIR/share/nest

# NEST finds help files \$NEST_DOC_DIR/help
setenv          NEST_DOC_DIR            \$INSTALLDIR/share/doc/nest

# The path where NEST looks for user modules.
setenv          NEST_MODULE_PATH        \$INSTALLDIR/lib64/nest

# The path where the PyNEST bindings are installed.
setenv          NEST_PYTHON_PREFIX      \$INSTALLDIR

prepend-path    PYTHONPATH              \$NEST_PYTHON_PREFIX
prepend-path    PATH                    \$INSTALLDIR/bin
#prepend-path    LD_LIBRARY_PATH  \$INSTALLDIR/lib64
#prepend-path    MANPATH \$INSTALLDIR/man

