#!/bin/bash
#
# This file is part of Builder.
#
# Builder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Builder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Builder.  If not, see <https://www.gnu.org/licenses/>.
#

# Here are some common definitions for all nest versions.
# Source this file from version specific build plans.

if [[ "$VERSION" =~ ^(2.14.0|2.16.0|2.18.0|2.20.0)$ ]];
then
	URL='https://github.com/nest/nest-simulator/archive/v${VERSION}.tar.gz'
fi

build_package () {
	log_status ">>> build"
	cd $BUILD
	set -x
	module load CMake/3.14.0
	module load Python/3.6.8
	module load SciPy-Stack/2019a-Python-3.6.8
	module load Intel/2019.5.281-GCC-8.3.0
	module load intel-para/2019a
	module load GSL/2.5
	module load jemalloc/5.1.0	
	# if version_gt 2.16.0 $VERSION; then # version 2.14.0 and before requrie LTDL as hard dependency
	#	module load libtool
	# fi

	cmake ${CMAKEFLAGS} -DCMAKE_INSTALL_PREFIX:PATH=$TARGET $SOURCE |& tee ${LOG}/cmake.log
	make -j ${MAKE_THREADS:-$(nproc)} |& tee ${LOG}/make.log
	set +x
}

build_install () {
	log_status ">>> install"
	make install |& tee ${LOG}/make-install.log
	awk 'BEGIN {f=3;x=0}; /^-------/{x=1;if (f>0) f--} f*x' ${LOG}/cmake.log >${TARGET}/ConfigurationSummary.txt
}

build_install_test () {
	log_status ">>> test"
	make installcheck |& tee ${LOG}/make-installcheck.log
	log_success "installcheck passed." >>${TARGET}/ConfigurationSummary.txt
	awk '/Testsuite Summary/{f=1} /Built target/{f=0} f;' ${LOG}/make-installcheck.log >>${TARGET}/ConfigurationSummary.txt
}
