#%Module1.0#####################################################################
#
# ${AUTOMATIC_BUILD_WARNING}
#
set     INSTALLDIR      "${TARGET}"

proc ModulesHelp { } {
        puts stderr "
   Bats is a TAP-compliant testing framework for Bash. It provides a simple way
   to verify that the UNIX programs you write behave as expected.

   A Bats test file is a Bash script with special syntax for defining test
   cases. Under the hood, each test case is just a function with a description.

   See https://github.com/bats-core/bats-core#bats-core-bash-automated-testing-system-2018
"
}

module-whatis   "Bash testing framework (${VERSION})"

conflict ${PACKAGE}
${PREREQ_DEPENDS}

prepend-path    PATH    \$INSTALLDIR/bin
prepend-path    MANPATH \$INSTALLDIR/share/man
