#%Module1.0#####################################################################
#
# ${PACKAGE}/${VERSION}/${VARIANT}
# ${AUTOMATIC_BUILD_WARNING}
#
proc ModulesHelp { } {
        puts stderr "MPC ${VERSION}-${VARIANT}"
}

module-whatis   "MPC ${VERSION}"

conflict ${PACKAGE}
${PREREQ_DEPENDS}

set     INSTALLDIR          "${TARGET}"

prepend-path    PATH    "\$INSTALLDIR/bin"
prepend-path    LD_LIBRARY_PATH  "\$INSTALLDIR/lib"
prepend-path    LIBRARY_PATH  "\$INSTALLDIR/lib"
prepend-path    CPATH    "\$INSTALLDIR/include"
prepend-path    MANPATH "\$INSTALLDIR/man"
