#!/bin/bash
#
# This file is part of Builder.
#
# Builder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Builder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Builder.  If not, see <https://www.gnu.org/licenses/>.
#

# from https://www.boost.org/users/download/
URL=https://dl.bintray.com/boostorg/release/${VERSION}/source/${PACKAGE}_${VERSION//./_}.tar.bz2

# boost_1_74_0.tar.bz2
SHA256SUM=83bfc1507731a0906e387fc28b7ef5417d591429e51e788417fe9ff025e116b1

