#%Module1.0#####################################################################
##
## ${PACKAGE} ${VERSION} (${VARIANT})
## ${AUTOMATIC_BUILD_WARNING}
##
set INSTALLDIR ${TARGET}

proc ModulesHelp { } {
        global VERSION
        puts stderr "${PACKAGE} ${VERSION}"
}

module-whatis   "${PACKAGE} ${VERSION} (${VARIANT})"

conflict ${PACKAGE}
${PREREQ_DEPENDS}

prepend-path    PATH    \$INSTALLDIR/bin
prepend-path    LD_LIBRARY_PATH  \$INSTALLDIR/lib
prepend-path    LIBRARY_PATH   \$INSTALLDIR/lib
prepend-path    CPATH   \$INSTALLDIR/include
prepend-path    MANPATH \$INSTALLDIR/share/man

