#!/bin/bash
#
# Builder – Compile scripts for local installs of software packages.
# Copyright (C) 2020 Forschungszentrum Jülich GmbH, INM-6
#
# Builder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Builder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Builder.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# from https://www.boost.org/users/download/
#URL=https://dl.bintray.com/boostorg/release/${VERSION}/source/${PACKAGE}_${VERSION//./_}.tar.bz2
URL=https://boostorg.jfrog.io/artifactory/main/release/${VERSION}/source/${PACKAGE}_${VERSION//./_}.tar.bz2

# boost_1_74_0.tar.bz2
SHA256SUM=83bfc1507731a0906e387fc28b7ef5417d591429e51e788417fe9ff025e116b1

# choice of "./bootstrap.sh --show-libraries"
LIBRARIES="test,random"

# https://www.boost.org/doc/libs/1_74_0/more/getting_started/unix-variants.html#easy-build-and-install
# Easy Build and Install
#
build_package () {
	log_status ">>> prepare build directory..."
	log_status "copying"
	log_status "   from source ${SOURCE}/*"
        log_status "   to   build  ${BUILD}"
	cp -r "${SOURCE}"/* "${BUILD}"

	log_status ">>> build ${PACKAGE}/${VERSION}/${VARIANT}..."
	cd "${BUILD}"
	set -x
	ls -lisa
	./bootstrap.sh --prefix="${TARGET}" --with-libraries="${LIBRARIES}"
	set +x
}

build_install() {
	log_status ">>> installing..."
	if [ -e "${TARGET}" ]; then
		log_warning "removing object at existing target location"
		rm -r "${TARGET}"
	fi
	./b2 install
}
