#!/bin/bash
#
# Builder – Compile scripts for local installs of software packages.
# Copyright (C) 2020 Forschungszentrum Jülich GmbH, INM-6
#
# Builder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Builder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Builder.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
URL=https://github.com/cea-hpc/modules/releases/download/v${VERSION}/modules-${VERSION}.tar.gz

# this checksum was not officially provided, but taken from downloaded tar-ball
SHA256SUM=ee7ecd62bbbde6d51e30788a97800c39e72515b6a910839fb84041b35ba42b4d

CONFIGURE_OPTIONS="--modulefilesdir '$MODULE_INSTALL_PATH'  --enable-color --disable-example-modulefiles"

build_package () {
	log_status ">>> in-tree build ${PACKAGE}/${VERSION}/${VARIANT}..."
	cd "${SOURCE}"
	set -x
	"./configure" --prefix="${TARGET}" ${CONFIGURE_OPTIONS:-} 2>&1 | tee "${LOG}/configure.log"
	make -j ${MAKE_THREADS:-$(nproc)} 2>&1 | tee "${LOG}/make.log"
	set +x
}
