#%Module1.0#####################################################################
##
## ${PACKAGE} ${VERSION} ${VARIANT}
##
set     INSTALLDIR      "${TARGET}"

proc ModulesHelp { } {
        puts stderr "${PACKAGE} ${VERSION} ${VARIANT}
--------------

   Source-to-Image (S2I) is a toolkit and workflow for building reproducible
   container images from source code. S2I produces ready-to-run images by
   injecting source code into a container image and letting the container
   prepare that source code for execution. By creating self-assembling builder
   images, you can version and control your build environments exactly like you
   use container images to version your runtime environments.

   Homepage / Documentation: https://github.com/openshift/source-to-image
   Source code: https://github.com/openshift/source-to-image/tree/v${VERSION}
"
}

module-whatis   "${PACKAGE} ${VERSION} : reproducibly build container images from source code"

conflict "${PACKAGE}"

prepend-path    PATH    \$INSTALLDIR
