#!/bin/bash
#
# This file is part of Builder.
#
# Builder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Builder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Builder.  If not, see <https://www.gnu.org/licenses/>.
#

URL=ftp://mama.indstate.edu/linux/${PACKAGE}/${PACKAGE}-${VERSION}.tgz

# this checksum was not officially provided, but taken from downloaded 1.8.0
# tar-ball
SHA256SUM=715d5d4b434321ce74706d0dd067505bb60c5ea83b5f0b3655dae40aa6f9b7c2


build_prepare() {
	log_status ">>> prepare build"
	if [ -d "${BUILD}" ]; then
		read -p "sure you want to delete ${BUILD}? (ctrl-c for NO)"
		rm -vrf "${BUILD}"
	fi
	# tree specific:
	mkdir -pv "$(dirname "${BUILD}")"
	cp -rv "${SOURCE}" "${BUILD}"	# not actually an out-of-tree-build
	cd "${BUILD}"
	sed -i -e "s%prefix = .*%prefix = ${TARGET}%" Makefile

	# write a dummy configure script, so that we can use Builder standard build_package()
	(
		cd "${SOURCE}"
		#test ! -e configure    # take care not to overwrite an eventually existing file
		echo "#!/bin/sh" >configure
		echo "echo 'dummy configure'" >>configure
		chmod u+x configure
	)
	mkdir -pv "${LOG}"
}

