#%Module1.0#####################################################################
#
# ${PACKAGE}/${VERSION}/${VARIANT}
# ${AUTOMATIC_BUILD_WARNING}
#
set     INSTALLDIR      "${TARGET}"

proc ModulesHelp { } {
        puts stderr "
   Tree is a recursive directory listing command that produces a depth indented
   listing of files, which is colorized ala dircolors if the LS_COLORS
   environment variable is set and output is to tty.
"
}

module-whatis   "graphical listing of directories (${VERSION})"

conflict ${PACKAGE}
${PREREQ_DEPENDS}

prepend-path    PATH    \$INSTALLDIR/bin
prepend-path    MANPATH \$INSTALLDIR/man
