#%Module1.0#####################################################################
##
## Tree
##
set     PACKAGE         ${PACKAGE}
set     VERSION         ${VERSION}
set     INSTALLDIR      ${TARGET}

proc ModulesHelp { } {
        global VERSION PACKAGE
        puts stderr "
   Tree is a recursive directory listing command that produces a depth indented
   listing of files, which is colorized ala dircolors if the LS_COLORS
   environment variable is set and output is to tty.
"
}

module-whatis   "graphical listing of directories (\$VERSION)"

conflict \$PACKAGE

prepend-path    PATH    \$INSTALLDIR/bin
prepend-path    MANPATH \$INSTALLDIR/man
