#!/bin/bash
#
# This file is part of Builder.
#
# Builder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Builder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Builder.  If not, see <https://www.gnu.org/licenses/>.
#

VERSION=${1:-1.8.0}
URL=ftp://mama.indstate.edu/linux/${PACKAGE}/${PACKAGE}-${VERSION}.tgz
# this checksum was not officially provided
SHA256SUM=715d5d4b434321ce74706d0dd067505bb60c5ea83b5f0b3655dae40aa6f9b7c2


build_prepare() {
	log_status ">>> prepare build"
	if [ -d "${BUILD}" ]; then
		read -p "sure you want to delete ${BUILD}? (ctrl-c for NO)"
		rm -vrf "${BUILD}"
	fi
	# tree specific:
	cp -rv "${SOURCE}" "${BUILD}"	# not actually an out-of-tree-build
	cd "${BUILD}"
	sed -i -e "s%prefix = .*%prefix = ${TARGET}%" Makefile
	mkdir -pv "${LOG}"
}

build_package () {
	log_status ">>> build"
	cd "${BUILD}"
	set -x
	make -j $(( $(nproc) / 4 )) |& tee "${LOG}/make.log"
	set +x
}
