#!/bin/bash
#
# Builder – Compile scripts for local installs of software packages.
# Copyright (C) 2020 Forschungszentrum Jülich GmbH, INM-6
#
# Builder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Builder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Builder.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
URL="https://github.com/bats-core/bats-core/archive/v${VERSION}.tar.gz"
MD5SUM="0df6b310c243503d8c28bc996b0a6002"
SHA256SUM="0f2df311a536e625a72bff64c838e67c7b5032e6ea9edcdf32758303062b2f3b"

build_prepare() {
	log_status ">>> nothing to prepare"
}
build_package() {
	log_status ">>> nothing to build"
}
build_install () {
	log_status ">>> installing..."
	cd "${SOURCE}"
	mkdir -pv "${LOG}"
	./install.sh "${TARGET}" 2>&1 | tee "${LOG}/make-install.log"
}
