#!/bin/bash
#
# Builder – Compile scripts for local installs of software packages.
# Copyright (C) 2020 Forschungszentrum Jülich GmbH, INM-6
#
# Builder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Builder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Builder.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
URL=https://github.com/plantuml/plantuml/releases/download/v${VERSION}/${PACKAGE}.jar
SHA256SUM=ee06454723028763dd8280459e8fd8f31fcd85b1ae8d9ab0e32122243c098c3b
#GPG_VERIFY_KEY="../plantuml-jar-signing-key.txt"

source_prepare() {
	log_status ">>> prepare source (from planfile)"
	check_package_file
}

build_prepare() {
	log_status ">>> nothing to build."
}

build_package() {
	log_status ">>> nothing to build."
}

build_install() {
	WRAPPER="${TARGET}/bin/plantuml"
	log_info "Installing shell wrapper at ${WRAPPER}"
	mkdir -pv "${TARGET}/bin"
	# wrapper similar to suggested by
	# https://daniel-siepmann.de/posts/migrated/workflow-for-read-the-docs-sphinx-and-plantuml.html
	cat >"${WRAPPER}" <<EOT
#!/usr/bin/env sh -e
java -Djava.awt.headless=true -jar "${TARGET}/${PACKAGE}-${VERSION}.jar" "\${@}"
EOT
	chmod u+x "${WRAPPER}"
	cp -v "${PACKAGE_FILE}" "${TARGET}/${PACKAGE}-${VERSION}.jar"
}
