#%Module1.0#####################################################################
#
# ${PACKAGE}/${VERSION}/${VARIANT}
# ${AUTOMATIC_BUILD_WARNING}
#
set INSTALLDIR "${TARGET}"

proc ModulesHelp { } {
        puts stderr "
   Tool which just does absolutely nothing (no-op).
"
}

module-whatis   "no-op tool (${VERSION})"

conflict ${PACKAGE}
${PREREQ_DEPENDS}

prepend-path    PATH    \$INSTALLDIR/bin
prepend-path    MANPATH \$INSTALLDIR/man
