#!/bin/bash
#
# Builder – Compile scripts for local installs of software packages.
# Copyright (C) 2020 Forschungszentrum Jülich GmbH, INM-6
#
# Builder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Builder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Builder.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
URL=https://github.com/Kitware/CMake/releases/download/v${VERSION}/${PACKAGE}-${VERSION}.tar.gz
MD5SUM=94a7befd2ff39721a3de844d94bd7c62

build_package () {
	log_status ">>> build"
	cd "${BUILD}"
	set -x
	"${SOURCE}/bootstrap" --prefix="${TARGET}" --parallel="${MAKE_THREADS:-$(nproc)}" |& tee "${LOG}/bootstrap.log"
	make -j "${MAKE_THREADS:-$(nproc)}" |& tee "${LOG}/make.log"
	set +x
}

