#!/bin/bash
#
# Builder – Compile scripts for local installs of software packages.
# Copyright (C) 2020 Forschungszentrum Jülich GmbH, INM-6
#
# Builder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Builder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Builder.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
URL=https://github.com/errata-ai/vale/releases/download/v${VERSION}/${PACKAGE}_${VERSION}_Linux_64-bit.tar.gz
SHA256SUM=7528175c995818bcb88b07574dd2e17c1aad13f5676880f43927bb8f673095aa

source_prepare() {
	check_package_file
	log_info "workaround for badly packaged zip-file..."
	if [ ! -d "${SOURCE}" ]; then
		mkdir -pv "${SOURCE}"
		cd "${SOURCE}"
		log_info "extracting ${PACKAGE_FILE}"
		tar -xzf "${PACKAGE_FILE}"
	fi
}

build_package () {
	log_status ">>> binary package is already built."
}

build_install () {
	log_status ">>> installing..."
	mkdir -pv "$(dirname "${TARGET}")"
	cp -vr "${SOURCE}"/* "${TARGET}"
}

build_install_test() {
	log_status ">>> test installed binary..."
	"${TARGET}"/vale -v
	log_info "vale was successfully called"
}
