#!/bin/bash
#
# This file is part of Builder.
#
# Builder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Builder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Builder.  If not, see <https://www.gnu.org/licenses/>.
#

URL=https://www.python.org/ftp/python/${VERSION}/Python-${VERSION}.tar.xz
# from downloaded  Python-3.8.5.tar.xz
SHA256SUM=e3003ed57db17e617acb382b0cade29a248c6026b1bd8aad1f976e9af66a83b0

CONFIGURE_OPTIONS="--enable-shared"
