#%Module1.0#####################################################################
##
## CMake
##
proc ModulesHelp { } {
        puts stderr "GMP ${VERSION}-${VARIANT}"
}

module-whatis   "GMP ${VERSION}"

conflict gmp

set     INSTALLDIR          "${TARGET}"

prepend-path    PATH    "\$INSTALLDIR/bin"
prepend-path    LD_LIBRARY_PATH  "\$INSTALLDIR/lib"
prepend-path    LIBRARY_PATH  "\$INSTALLDIR/lib"
prepend-path    CPATH    "\$INSTALLDIR/include"
prepend-path    MANPATH "\$INSTALLDIR/man"
