#%Module1.0#####################################################################
##
## CMake
##
proc ModulesHelp { } {
        puts stderr "MPFR ${VERSION}-${VARIANT}
--------------------------------

Documentation: https://www.mpfr.org/mpfr-current/mpfr.html"
}

module-whatis   "MPFR ${VERSION}"

conflict mpfr

set     INSTALLDIR          "${TARGET}"

prepend-path    PATH    "\$INSTALLDIR/bin"
prepend-path    LD_LIBRARY_PATH  "\$INSTALLDIR/lib"
prepend-path    LIBRARY_PATH  "\$INSTALLDIR/lib"
prepend-path    CPATH    "\$INSTALLDIR/include"
prepend-path    MANPATH "\$INSTALLDIR/man"
