#!/bin/bash
#
# Builder – Compile scripts for local installs of software packages.
# Copyright (C) 2020 Forschungszentrum Jülich GmbH, INM-6
#
# Builder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Builder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Builder.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

# This is a script collection that does not require build.
# The "install" is creation of a single symlink.

source_prepare() {
        log_status ">>> no source preparation necessary."
}

build_prepare() {
        log_status ">>> no prepare for pip packages."
}

build_package () {
        log_status ">>> build phase is combined with install phase for pip packages."
}

build_install () {
        log_status ">>> build and install ${PACKAGE}..."
	set -x
	if [ -d "${TARGET}" ]; then
                read -r -p "sure you want to delete ${TARGET}? (ctrl-c for NO)"
                rm -vrf "${TARGET}"
        fi
	#git clone --depth 1 -b "${VARIANT}" "git@github.com:INM-6/${PACKAGE}.git" "${TARGET}"
	git clone --depth 1 -b "master" "git@github.com:INM-6/${PACKAGE}.git" "${TARGET}"
	HERE="$(pwd)"
	cd "${TARGET}"
	ln -s build.sh build
	chmod u+x build.sh
	cd "${HERE}"
	set +x
}

