#!/bin/bash
#
# Builder – Compile scripts for local installs of software packages.
# Copyright (C) 2020 Forschungszentrum Jülich GmbH, INM-6
#
# Builder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Builder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Builder.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

# NEST Simulator 2.18.0
DOI=10.5281/zenodo.2605422
MD5SUM=5d04f99bb8d1fa13a5796ef12500ec99
SHA256SUM=7295c936fbdd5486395b06f54f0d4d35d9a1b6ee50b7b844186ec2c92de641d1

# shellcheck source=plans/nest-simulator/common
source "$(dirname "${PLAN}")/../common"
