#!/bin/bash
#
# This file is part of Builder.
#
# Builder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Builder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Builder.  If not, see <https://www.gnu.org/licenses/>.
#

URL=https://download.schedmd.com/${PACKAGE}/${PACKAGE}-${VERSION}.tar.bz2

# from https://www.schedmd.com/downloads.php
# slurm-20.02.5.tar.bz2
SHA1SUM=62d9f66c86e17cbc541328e5f36a1213eaf7789a
MD5SUM=3902c8a06643cf70cf6fe750971f7146
SHA256SUM=c32a7a32010a526bb8a303df1df081c79dbe15423576543a73c65bdd33301723

CONFIGURE_OPTIONS="--enable-deprecated"

