#!/bin/bash
#
# Builder – Compile scripts for local installs of software packages.
# Copyright (C) 2020 Forschungszentrum Jülich GmbH, INM-6
#
# Builder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Builder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Builder.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
URL=https://github.com/Kitware/CMake/releases/download/v${VERSION}/${PACKAGE}-${VERSION}.tar.gz
MD5SUM=bc0d668dba6ec081c664ae95b75540d6
SHA256SUM=c0e3338bd37e67155b9d1e9526fec326b5c541f74857771b7ffed0c46ad62508

build_package () {
	log_status ">>> build"
	cd "${BUILD}"
	set -x
	"${SOURCE}/bootstrap" --prefix="${TARGET}" --parallel="${MAKE_THREADS:-$(nproc)}" |& tee "${LOG}/bootstrap.log"
	#./bootstrap --prefix="${TARGET}" --srcdir="${SOURCE}" |& tee "${LOG}/bootstrap.log"
	make -j "${MAKE_THREADS:-$(nproc)}" |& tee "${LOG}/make.log"
	set +x
}

