name: Tests
on: [push, pull_request]
jobs:
  BATS:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04"]
        envmodules: ["environment-modules=4.4.*", "lmod=6.6-*"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Install ${{ matrix.envmodules }}
      run: sudo apt install ${{ matrix.envmodules }}

    - name: Install test dependencies
      run: sudo apt install shellcheck

    - name: Install BATS
      run: |
        source /etc/profile
        ./build.sh configure || true
        module --version
        if [ $LMOD_VERSION+x ]; then
          echo "assuming LUA modules…"
        else
          echo "assuming TCL modules…"
        fi
        ./build.sh -s bats

    - name: Run BATS
      env:
        LATEST_BATS_VER: 1.8.2
      run: |
        source /etc/profile
        module --version
        module use /home/runner/modules
        echo "MODULEPATH=$MODULEPATH"
        find /home/runner/modules -type f
        set
        echo "module avail:"
        module --ignore_cache avail
        module load bats/${LATEST_BATS_VER}/default
        bats tests/
