name: Tests
on: [push, pull_request]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install environment-modules
      run: sudo apt-get install environment-modules
    - name: Install BATS
      run: |
        ./build.sh configure || true
        echo "y" | ./build.sh bats
    - name: Run BATS
      run: |
        export MODULEPATH=$MODULEPATH:/home/runner/modules
        module load bats
        bats tests/
