name: Tests
on: [push, pull_request]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install BATS
      run: |
        ./build.sh configure || true
        yes | ./build.sh bats
    - name: Run BATS
      run: bats tests/
