name: Tests
on: [push, pull_request]
jobs:
  BATS:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04"]
        envmodules: ["environment-modules=4.4.*", "lmod=6.6-*"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install ${{ matrix.envmodules }}
      run: sudo apt-get install ${{ matrix.envmodules }}
    - name: Install BATS
      run: |
        ./build.sh configure || true
        echo "y" | ./build.sh bats
    - name: Run BATS
      run: |
        source /etc/profile
        echo "MODULEPATH=$MODULEPATH"
        #export MODULEPATH=/home/runner/modules:$MODULEPATH
        module use /home/runner/modules
        echo "MODULEPATH=$MODULEPATH"
        find /home/runner/modules -type f
        echo "module avail / spider"
        module spider || true   # not fail if spider not found
        module avail
        date
        echo "run tests"
        module load bats
        bats tests/
